site_title = "MyArxiv"
limit_days = 14
cache_url = "https://vvvvhao.github.io/MyArixiv/cache.json"

[[sources]]
limit = 150
category = "cs.CL"
title = "Computation and Language"

[[sources]]
limit = 150
category = "stat.ME"
title = "Statistic methodology"

[[sources]]
limit = 150
category = "cs.AI"
title = "CS Artificial Intelligence"

[[sources]]
limit = 150
category = "cs.LG"
title = "CS Machine Learning"

[[sources]]
limit = 150
category = "stat.ML"
title = "Statistic Machine Learning"

[[sources]]
limit = 150
category = "math.NA"
title = "Numerical analysis"

[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
